
export const START_FETCHING_PROJECT_LIST = 'START_FETCHING_PROJECT_LIST';
export const FINISH_FETCHING_PROJECT_LIST = 'FINISH_FETCHING_PROJECT_LIST';
export const FAILURE_FETCHING_PROJECT_LIST = 'FAILURE_FETCHING_PROJECT_LIST';

export const START_FETCHING_PROJECT_OVERVIEW = 'START_FETCHING_PROJECT_OVERVIEW';
export const FINISH_FETCHING_PROJECT_OVERVIEW = 'FINISH_FETCHING_PROJECT_OVERVIEW';
export const FAILURE_FETCHING_PROJECT_OVERVIEW = 'FAILURE_FETCHING_PROJECT_OVERVIEW';

export const FETCH_PROJECT_INFO = 'FETCH_PROJECT_INFO';